apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rjm9a8lrg-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rjm9a8lrg-java-springboot-gitops